### PR TITLE
charcoal

### PR DESCRIPTION
**Pull request by michaelthe**
#26

### CODE REVIEW

**Comment by michaelthe** [comment]
i believe we have to think a better colour coding.
maybe based on functionality api and ws have deferent colours etc

**Comment by michaelthe** [comment]
also wrong branch name

**Comment by pitops** [comment]
```
i believe we have to think a better colour coding.
maybe based on functionality api and ws have deferent colours etc
```

Thats why we use the prefix `Puppy API` and `Puppy WS`. Maybe we can throw that into `charcoal.js` as well?

**Comment by michaelthe** [comment]
ready to be merged to test run npm run test-verbose

**Pull request merged**
