### PR TITLE
Added Socket Receive Capability

### PR DESCRIPTION
**Pull request by BlackConure**
Ok, I have updated the code to allow for socket messages to be received and handled.   I updated the README.md file with information about how to configure and use them.   

Let me know what you think!

### CODE REVIEW

**Comment by michaelthe** [comment]
Hi @BlackConure.
Thanks for the pull request.
Unfortunately its a bit difficult for us to check the PR. because of the noise ; added.
can you please use [StandardJS](https://standardjs.com/) style with 2 spaces instead of tabs.

**Comment by BlackConure** [comment]
Ok, let me see what I can do.   I use Prettier style, but I think there may be a way I can have it conform to Standard style and re-submit.

**Comment by BlackConure** [comment]
I ran it through Standard style in Prettier.   I hope the default settings were ok.   Let me know if this is better.

**Comment by michaelthe** [comment]
@BlackConure Thanks for the update.
We will accept the changes put will change some things in order to fit the new feature to our vision.
Thank you for the contribution

**Comment by BlackConure** [comment]
Thanks, I was expecting some changes....it was just a kick starter.   Btw:  I found a bug in that on a receive, I made the interval optional.   There is one case where it errors when the interval is not specified.

Also, there seems to be an issue with accessing the sockets from chrome.   It connects, but the emit never happens (works fine with Apic).   I think it may be a cors issue, but haven't confirmed this yet. 

I noticed cors was used on socket.io, should that work for sockets as well as http, or is there more that needs to be done.   What about client side?  

Client connects but no emits occur.  Thoughts?

**Pull request merged**
